apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: demo-voting-app
spec:
  type: LoadBalancer
  selector:
    app: demo-voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
